site_name: Tech Writing Templates
nav:
- Home: docs/index.md
- Templates: docs/templates.md
- Template Documents:
  - Documento di Requisiti: docs/Templates/001-documento-requisiti.md
  - Specifiche Funzionali: docs/Templates/002-specifiche-funzionali.md
  - Specifiche Tecniche: docs/Templates/003-specifiche-tecniche.md
  - Architettura del Sistema: docs/Templates/004-architettura-sistema.md
  - Piano di Progetto: docs/Templates/005-piano-progetto.md
  - Documentazione API: docs/Templates/006-documentazione-api.md
  - Manuale Utente: docs/Templates/007-manuale-utente.md
  - Guida per Sviluppatori: docs/Templates/008-guida-sviluppatori.md
  - Piano di Test: docs/Templates/009-piano-test.md
  - Release Notes: docs/Templates/010-release-notes.md
  - Documento di Design: docs/Templates/011-documento-design.md
  - README: docs/Templates/012-README.md
  - Changelog: docs/Templates/013-changelog.md
  - Documento di Sicurezza: docs/Templates/014-documento-sicurezza.md
  - Manuale di Installazione: docs/Templates/015-manuale-installazione.md
theme:
  name: material